config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, path: 'admins', controllers: { sessions: "users/sessions",registrations: "users/registrations"}
  devise_for :users, path: 'users', controllers: { sessions: "admins/sessions", registrations: "admins/registrations" }
  #match "*path" => redirect("https://www.maksite.eu/%{path}"),via: [:get, :post], :constraints => { :protocol => "http://" }
  #match "*path" => redirect("https://www.maksite.eu/%{path}"),via: [:get, :post], :constraints => { :subdomain => "" }
  get 'articles/new'

  root 'home#home'

  resources :articles do
    resources :comments
  end



  get 'links/links'

  get 'about/about'

  get 'contact/contact'

  get 'contact/form'

  get 'projects/projects'

  get 'news/news'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
Rails.application.config.active_record.sqlite3.represent_boolean_as_integer = true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments
	has_many :categories
	has_one_attached :image
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def about
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authenticate_admin!, :except => [:sign_in, :show]
	helper_method :sort_direction
	def index
		@articles = Article.all
	end
	def show
    	@article = Article.find(params[:id])
  	end
	def new
		@article = Article.new
	end
	def edit
		@article = Article.find(params[:id])
	end
	def update
  		@article = Article.find(params[:id])
 
  		if @article.update(article_params)
    		redirect_to @article
  		else
    		render 'edit'
  		end
	end
	def create
		@article = Article.new(article_params)
 		@article.save
 		redirect_to @article
	end
	def destroy
   		@article = Article.find(params[:id])
   		@article.destroy
   		redirect_to articles_path, notice: "Delete success"
	end
	private
  	def article_params
    	params.require(:article).permit( :title, :text, :image, :tag)
  	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:article_id, :title, :content)
    end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def contact
  end

  def form
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  	if Article.exists?
  		@article = Article.order('created_at').last
  	end
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def links
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
	helper_method :sort_direction
	
	def news
		if params[:column] == 'title'
			@articles = Article.all.order("title #{sort_direction}")
		elsif params[:column] == 'created_at'
			@articles = Article.all.order("created_at #{sort_direction}")
		else
			@articles = Article.all
		end	
	end

	def sortByTag
		order(tag: :asc).page(params[:articles]).per(20)
	end

		private

		def sort_direction
			%w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
		end
	end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def projects
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def sortable(title, column, direction)
		direction = sort_direction == "asc" ? "desc" : "asc"
		icon = sort_direction == 'desc' ? 'down' : 'up'

		link_to news_news_path(:column =>column, :direction =>direction), class: 'tiny button secondary', id: column do
			"#{title} &nbsp; <i class=fi-arrow-#{icon}></i>".html_safe
		end
	end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.haml
%h1 Edit Article
%br/
%hr/
.article-preview.col-lg-12
  = form_with(model: @article) do |form|
    - if @article.errors.any?
      #error_explanation
        %h2
          = pluralize(@article.errors.count, "error")
          prohibited
          this article from being saved:
        %ul
          - @article.errors.full_messages.each do |msg|
            %li= msg
    %p
      = form.label :title
      %br/
      = form.text_field :title
    %p
      = form.label :text
      %br/
      = form.text_area :text
    %p
      = form.label :image, :name => "Image: "
      %br/
      = form.file_field :image
    %p
      = form.label :tag
      = form.text_field :tag
    %br/
    %p
      = form.submit class: 'btn-primary'
= link_to 'Back', articles_path, :class => "btn btn-info", :style => "margin: 1rem;"

app/views/articles/index.html.haml
%h1{:style => "font-family:lora"} Listing Articles
%br
%hr
%p 
 = link_to 'New Article', new_article_path, :class=> "btn btn-primary"
 %p Sort by: 
 = link_to "Time", articles_path(order: 'time')
 = link_to "Tag", articles_path(order: 'tag')
 = link_to "Title", articles_path(order: 'title')
.article-preview.col-lg-12
 - @articles.each do |article|
  = link_to image_tag(article.image), article.image
  = article.title.html_safe
  = article.text.html_safe 
  = link_to 'Delete', article_path(article), method: :delete, data: { confirm: 'Are you sure?' },  :class=> "btn btn-danger"                          
  = link_to 'Edit', edit_article_path(article), :class=> "btn btn-secondary"
  = link_to 'Show', article, :class=> "btn btn-info"
  %hr

app/views/articles/new.html.erb
<h1>New Article</h1>
<br>
<hr>
<div class="article-preview col-lg-12">
<%= form_for @article, :html => { multipart: true } do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text, :style => "resize:both;" %>
  </p>
  <p>
  <%= form.label :image %>
  <%= form.file_field :image %>
  </p>
  <p>
  <%= form.label :tag %>
  <%= form.text_field :tag %>
  </p>
  <p>
    <%= form.submit class: 'btn-primary' %>
  </p>
<% end %>
</div>
<%= link_to 'Back', articles_path, :class => "btn btn-info", :style => "margin: 1rem;"%>

app/views/articles/show.html.haml
.article-detailed
 = image_tag(@article.image)
 %h1
  = @article.title.html_safe
 %p
  = @article.text.html_safe
 %p.tag 
  = 'Category:'
  = @article.tag
 .mini-footer
  = link_to 'Back', news_news_path, class: "btn btn-info btn-back"
  = @article.created_at.strftime("%d/%m/%Y")
 -#= render 'comments/index'
 -#= render 'comments/form'

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :article_id %>
    <%= form.number_field :article_id %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/_show.html.haml
- @article.comments.each do |comment|
 .comment_field
  %h5="#{comment.user.email}"
  %h6="#{comment.created_at}"
  %p=comment.content
  %hr

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Article</th>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.article_id %></td>
        <td><%= comment.title %></td>
        <td><%= comment.content %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Article:</strong>
  <%= @comment.article_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @comment.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>