config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, path: 'admins', controllers: { sessions: "users/sessions",registrations: "users/registrations"}
  devise_for :users, path: 'users', controllers: { sessions: "admins/sessions", registrations: "admins/registrations" }
  #match "*path" => redirect("https://www.maksite.eu/%{path}"),via: [:get, :post], :constraints => { :protocol => "http://" }
  #match "*path" => redirect("https://www.maksite.eu/%{path}"),via: [:get, :post], :constraints => { :subdomain => "" }
  get 'articles/new'

  root 'home#home'

  resources :articles do
    resources :comments
  end



  get 'links/links'

  get 'about/about'

  get 'contact/contact'

  get 'contact/form'

  get 'projects/projects'

  get 'news/news'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
Rails.application.config.active_record.sqlite3.represent_boolean_as_integer = true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments
	has_many :categories
	has_one_attached :image
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def about
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def contact
  end

  def form
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  	if Article.exists?
  		@article = Article.order('created_at').last
  	end
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def links
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
	helper_method :sort_direction
	
	def news
		if params[:column] == 'title'
			@articles = Article.all.order("title #{sort_direction}")
		elsif params[:column] == 'created_at'
			@articles = Article.all.order("created_at #{sort_direction}")
		else
			@articles = Article.all
		end	
	end

	def sortByTag
		order(tag: :asc).page(params[:articles]).per(20)
	end

		private

		def sort_direction
			%w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
		end
	end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def sortable(title, column, direction)
		direction = sort_direction == "asc" ? "desc" : "asc"
		icon = sort_direction == 'desc' ? 'down' : 'up'

		link_to news_news_path(:column =>column, :direction =>direction), class: 'tiny button secondary', id: column do
			"#{title} &nbsp; <i class=fi-arrow-#{icon}></i>".html_safe
		end
	end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Maksite
    %meta{:name=>"viewport",:content=>"width=device-width, initial-scale=1.0"}
    = csrf_meta_tags
    = favicon_link_tag 'favicon.ico' 
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Inconsolata%7CLato%7CLora%7CManuale'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    #background
      .row
        %nav.navbar.navbar-inverse.navbar-expand-lg.navbar-dark.bg-dark.navbar-left
          %ul.nav.navbar-nav.navbar-left
            %li.nav-item.btn
              = link_to raw("<i class=\"fa fa-home\"></i>"),root_path,:class =>'navbar-brand active', :method => :get
          %button.navbar-toggler{ "data-toggle"=>"collapse", "data-target" => "#navbarNavDropdown", "aria-controls" => "navbarNavDropdown", "aria-expanded" => "true", "aria-label" => "Toggle navigation"}
            %span.navbar-toggler-icon
          .collapse.navbar-collapse#navbarNavDropdown
            %ul.nav.navbar-nav.navbar-right
              %li.nav-item.btn 
                = link_to "News", news_news_path, :class =>'nav-link'
              %li.nav-item.btn
                = link_to "About me", about_about_path, :class =>'nav-link'
              %li.nav-item.btn
                = link_to "Contact", contact_contact_path, :class =>'nav-link'  
              %li.nav-item.btn
                = link_to "Links", links_links_path, :class =>'nav-link'
      .maincontainer
        = yield 
        %p.notice
          = notice
        %p.alert
          = alert
      %footer.footer-dark.bg-dark
        %p#sessionDialog
          - if current_user 
            = "Logged as"
            %span#usertag= "#{current_user_user.email}"
          - if !current_admin.nil?
            = "Greetings commander,"
            %span#usertag= "#{current_admin.email}"
        %h1{:style=>"font-size: 20px;"}
          = raw('Maksym Zieliński') 
          = Time.current.year
          = "&copy;".html_safe
        = link_to '<i class="fab fa-linkedin" aria-hidden="true"></i>'.html_safe, "https://pl.linkedin.com/in/maksym-zieliński-077747133", :id => "linked-icon" 
        = link_to '<i class="fab fa-facebook-square" aria-hidden="true"></i>'.html_safe, "https://www.facebook.com/maksym.zielinski.3", :id => "facebook-icon"
        = link_to '<i class="fab fa-linode" aria-hidden="true"></i>'.html_safe, "https://www.linode.com", :id => "linode-icon"
        = link_to '<i class="far fa-gem" aria-hidden="true"></i>'.html_safe, "https://www.ruby-lang.org/", :id => "ruby-icon"
        = link_to '<i class="fa fa-wrench" aria-hidden="true"></i>'.html_safe, articles_path, :id => "wrench-icon"
        - if current_admin
          = link_to '<i class="fa fa-power-off" aria-hidden="true"></i>'.html_safe, destroy_admin_session_path, :id => "off-icon", method: :delete
        - if current_user
          = link_to '<i class="fa fa-power-off" aria-hidden="true"></i>'.html_safe, destroy_user_session_path, :id => "off-icon", method: :delete

          